### ISSUE TITLE
Upgrade to Tokio v1.0

### ISSUE THREAD

**Issue by 1tgr** [1tgr/rust-websocket-lite#108]
* [x] update codec and client: done in #115
* [x] update hyper: waiting on hyperium/hyper#2302
* [x] update tokio-openssl: waiting on release of sfackler/tokio-openssl#24 to crates.io
* [x] update tokio-native-tls: waiting on tokio-rs/tls#47

**Comment by 1tgr** [comment]
Currently waiting on hyper: hyperium/hyper#2302

**Comment by hyyking** [comment]
partially closed by #115

**Comment by 1tgr** [comment]
hyper skipped tokio v0.3. hyper v0.14 depends on tokio v1.0 instead.

**Comment by 1tgr** [comment]
* bytes: `bytes()` -> `chunk()`
* hyper: server code requires `features=["server"]`
